FROM mongo:6.0

# Add MongoDB configuration
COPY mongo-init.js /docker-entrypoint-initdb.d/

# Set the data directory for MongoDB
VOLUME /data/db

# MongoDB port
EXPOSE 27017

# MongoDB will start automatically as the CMD is defined in the base mongo image
