version: '3.8'

services:
  # MongoDB Database
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    image: gupta9939/e_health_management:03
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - telemedicine-network
    restart: unless-stopped

  # Node.js Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gupta9939/e_health_management_backend:03
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/telemedicine?connectTimeoutMS=5000&serverSelectionTimeoutMS=5000
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - telemedicine-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: gupta9939/e_health_management_frontend:03
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - telemedicine-network
    restart: unless-stopped

networks:
  telemedicine-network:
    driver: bridge

volumes:
  mongodb_data:
